baseURL = "https://blissful-archimedes-9aa76d.netlify.com"
languageCode = "en-us"
title = "euri.ca"
theme = "hyde"


[permalinks]
  post = "/:year/:month/:title/"

[params]
  themeColor = "theme-base-0d"
  description = "Numbers for people"
  copyright = "Content from 2005-2018. dave@euri.ca"